# ===============================
# PHP version control (future)
# ===============================
ARG PHP_VERSION=8.4

# Base Image
FROM php:${PHP_VERSION}-fpm-alpine AS codexsun-laravel

LABEL maintainer="codexsun"
LABEL author="Sundar < sundar@sundar.com >"
LABEL version="2.0"
LABEL description="codexsun - Node Js + Laravel development"

# Install required packages
RUN apk add --no-cache \
    bash \
    git \
    nano \
    sudo \
    curl \
    unzip \
    zip \
    icu-dev \
    oniguruma-dev \
    libxml2-dev \
    libzip-dev \
    libpng-dev \
    libxslt-dev \
    libjpeg-turbo-dev \
    freetype-dev \
    postgresql-dev \
    mariadb-connector-c-dev \
    sqlite-dev \
    zlib-dev \
    linux-headers \
    nodejs \
    npm


# -----------------------------
# PHP extensions (Laravel)
# -----------------------------
RUN docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install \
        pdo_mysql \
        pdo_pgsql \
        mbstring \
        bcmath \
        exif \
        pcntl \
        gd \
        zip \
        intl \
        xsl

# -----------------------------
# Composer
# -----------------------------
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# -----------------------------
# PHP recommended settings
# -----------------------------
RUN echo "memory_limit=512M" > /usr/local/etc/php/conf.d/laravel.ini \
 && echo "upload_max_filesize=50M" >> /usr/local/etc/php/conf.d/laravel.ini \
 && echo "post_max_size=50M" >> /usr/local/etc/php/conf.d/laravel.ini \
 && echo "max_execution_time=120" >> /usr/local/etc/php/conf.d/laravel.ini


# Create non-root user 'devops' and grant sudo privileges
RUN adduser -D devops && \
    echo "devops ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# Create working directory
RUN mkdir -p /home/devops/cloud && \
    chmod -R 755 /home/devops/cloud

# Install pnpm as root (with correct permissions)
USER root
RUN npm install -g pnpm@latest --unsafe-perm=true

# Fix ownership of global npm directories (for devops user)
RUN chown -R devops:devops /usr/local/lib /usr/local/bin /home/devops

# Switch to non-root user for safer runtime
USER devops

# Set working directory
WORKDIR /home/devops/cloud

# Expose dev ports
EXPOSE 3006
EXPOSE 5006

# Use environment variables for flexibility
ENV HOST=0.0.0.0
ENV PORT=3006

# Start the app
CMD ["bash"]