services:
  erp_techmedia_co_in:
    image: cloudxis:v2
    container_name: erp_techmedia_co_in
    ports:
      - "8001:8000"
      - "5001:5001"
      - "3001:3001"
    volumes:
      - ../../../../cloud/erp_techmedia_co_in:/home/devops/cloud
    networks:
      - codexion-network
    restart: unless-stopped
    tty: true

networks:
  codexion-network:
    external: true