services:
  lifeshoppy_com:
    image: cloudxis:v2
    container_name: lifeshoppy_com
    ports:
      - "8001:8000"
      - "5001:5001"
      - "3001:3001"
    volumes:
      - ../../../../cloud/lifeshoppy_com:/home/devops/cloud
    networks:
      - codexion-network
    restart: unless-stopped
    tty: true

networks:
  codexion-network:
    external: true