services:
  techmedia_in:
    image: cloudxis:v2
    container_name: techmedia_in
    ports:
      - "8005:8000"
      - "5005:5005"
      - "3005:3005"
    volumes:
      - ../../apps/devops/techmedia_in/cloud:/home/devops/cloud
    networks:
      - codexion-network
    restart: unless-stopped
    tty: true

networks:
  codexion-network:
    external: true