services:
  aaranwebs:
    image: codexsun:v6
    container_name: aaranwebs
    ports:
      - "7021:8000"
    volumes:
        - ../../../cloud/aaranwebs:/app
    networks:
      - codexion-network
    restart: unless-stopped
    environment:
      APP_ENV: local
      APP_DEBUG: "false"
    tty: true

networks:
  codexion-network:
    external: true