services:
  aaranwebs:
    image: codexion:v5
    container_name: aaranwebs
    ports:
      - "7021:7021"
      - "7022:7022"
    volumes:
      - ../../../cloud/demo_codexsun_com:/home/devops/cloud
    networks:
      - codexion-network
    restart: unless-stopped
    tty: true

networks:
  codexion-network:
    external: true