services:
  aaranwebs:
    image: codexsun:v6
    container_name: aaranwebs
    ports:
      - "80:80"
      - "443:443/tcp"
      - "443:443/udp"
      - "7021:80"
    volumes:
      - ../../../cloud/aaranwebs:/app
    networks:
      - codexion-network
    restart: unless-stopped
    environment:
      APP_ENV: local
      APP_DEBUG: "false"
    tty: true

networks:
  codexion-network:
    external: true