services:
  erp_ttt_com:
    image: codexion:v5
    container_name: erp_ttt_com
    ports:
      - "8001:8000"
      - "7001:7000"
      - "6001:6000"
      - "5001:5000"
    volumes:
      - ../../../cloud/erp_ttt_com:/home/devops/cloud
    networks:
      - codexion-network
    restart: unless-stopped
    tty: true

networks:
  codexion-network:
    external: true