services:
  tmwebs:
    image: codexion:v5
    container_name: tmwebs
    ports:
      - "7020:7020"
      - "7021:7021"
      - "7022:7022"
      - "7023:7023"
      - "7024:7024"
      - "7025:7025"
    volumes:
      - ../../../cloud/tmwebs:/home/devops/cloud
    networks:
      - codexion-network
    restart: unless-stopped
    tty: true

networks:
  codexion-network:
    external: true