# =========================================================
# Codexion Cloud – Ubuntu 24.04 + Python 3.14 + Frappe Bench
# =========================================================

FROM ubuntu:24.04

LABEL maintainer="codexion"
LABEL author="Sundar <sundar@sundar.com>"
LABEL version="2.0"
LABEL description="Ubuntu 24.04 + Python 3.14 (pyenv) + Frappe Bench"

ENV DEBIAN_FRONTEND=noninteractive
ENV LANG=en_US.UTF-8

# ---------------------------------------------------------
# System dependencies (NO system python)
# ---------------------------------------------------------
RUN apt-get update && apt-get install -y --no-install-recommends \
  build-essential curl wget git sudo nano unzip ca-certificates bash-completion \
  software-properties-common net-tools iputils-ping tree less watch file rlwrap make \
  htop lsof rsync gnupg2 tar gzip zip bzip2 xz-utils \
  openssh-server openssh-client vsftpd openssl \
  vim locales lsb-release cron supervisor nginx \
  mariadb-client libmariadb-dev \
  postgresql-client libpq-dev \
  redis redis-server redis-tools \
  libssl-dev libffi-dev libldap2-dev libsasl2-dev \
  zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev \
  libncursesw5-dev libncurses5-dev tk-dev liblzma-dev llvm \
  fonts-cantarell xfonts-75dpi xfonts-base \
  libpango-1.0-0 libharfbuzz0b libpangoft2-1.0-0 libpangocairo-1.0-0 \
  libjpeg-turbo8 libxrender1 \
  pkg-config media-types \
  glances iftop psutils gh \
  && locale-gen en_US.UTF-8 \
  && apt-get clean && rm -rf /var/lib/apt/lists/*

# ---------------------------------------------------------
# wkhtmltopdf (ERPNext compatible)
# ---------------------------------------------------------
RUN cd /tmp && \
  wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-2/wkhtmltox_0.12.6.1-2.jammy_amd64.deb && \
  apt-get update && apt-get install -y ./wkhtmltox_0.12.6.1-2.jammy_amd64.deb && \
  rm wkhtmltox_0.12.6.1-2.jammy_amd64.deb && \
  apt-get clean && rm -rf /var/lib/apt/lists/*

# ---------------------------------------------------------
# Create devops user
# ---------------------------------------------------------
RUN groupadd devops && \
    useradd -m -g devops -s /bin/bash devops && \
    echo 'devops ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

# ---------------------------------------------------------
# Switch to devops user
# ---------------------------------------------------------
USER devops
WORKDIR /home/devops

# ---------------------------------------------------------
# pyenv + Python 3.14 ONLY
# ---------------------------------------------------------
ENV PYENV_ROOT=/home/devops/.pyenv
ENV PATH=$PYENV_ROOT/bin:$PYENV_ROOT/shims:$PATH
ENV PYTHON_VERSION=3.14.2

RUN git clone --depth 1 https://github.com/pyenv/pyenv.git $PYENV_ROOT \
    && pyenv install $PYTHON_VERSION \
    && pyenv global $PYTHON_VERSION \
    && pip install --upgrade pip setuptools wheel virtualenv

RUN echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc \
    && echo 'export PATH="$PYENV_ROOT/bin:$PYENV_ROOT/shims:$PATH"' >> ~/.bashrc \
    && echo 'eval "$(pyenv init --path)"' >> ~/.profile \
    && echo 'eval "$(pyenv init -)"' >> ~/.bashrc

# ---------------------------------------------------------
# Node.js via NVM
# ---------------------------------------------------------
ENV NVM_DIR=/home/devops/.nvm
ENV NODE_VERSION=24.12.0
ENV PATH=$NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH

RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash \
    && . "$NVM_DIR/nvm.sh" \
    && nvm install $NODE_VERSION \
    && nvm use $NODE_VERSION \
    && nvm alias default $NODE_VERSION \
    && npm install -g yarn \
    && rm -rf $NVM_DIR/.cache

# ---------------------------------------------------------
# Install Frappe Bench
# ---------------------------------------------------------
ENV PATH=/home/devops/.local/bin:$PATH

RUN git clone --depth 1 -b v5.x https://github.com/frappe/bench ~/.bench \
    && pip install --user -e ~/.bench \
    && echo 'export PATH="$HOME/.local/bin:$PATH"' >> ~/.bashrc \
    && echo 'export BENCH_DEVELOPER=1' >> ~/.bashrc

# ---------------------------------------------------------
# Root links & supervisor
# ---------------------------------------------------------
USER root
RUN ln -sf /home/devops/.local/bin/bench /usr/local/bin/bench \
    && mkdir -p /var/log/supervisor

COPY supervisord.conf /etc/supervisor/supervisord.conf

RUN mkdir -p /home/devops
COPY init_frappe.py /home/devops/ifrappe.py
RUN chmod +x /home/devops/ifrappe.py \
    && ln -s /home/devops/ifrappe.py /usr/local/bin/ifrappe

USER devops
WORKDIR /home/devops

RUN mkdir -p /home/devops/logs

EXPOSE 8000 8888

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf"]

SHELL ["/bin/bash", "-c"]
