services:
  ttt_com:
    image: codexsun:v4
    container_name: ttt_com
    ports:
      - "8000:8000"
      - "5001:5001"
      - "3001:3001"
    volumes:
      - ../../apps/devops/cloud:/home/devops/cloud
    networks:
      - codexion-network
    restart: unless-stopped
    tty: true

networks:
  codexion-network:
    external: true